timeout: 3600s
steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  dir: terraform/single/
  env:
  - "TF_IN_AUTOMATION=true"
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init -input=false
- id: 'tf destroy plan'
  name: 'hashicorp/terraform:1.0.0'
  dir: terraform/single/
  env:
  - "TF_IN_AUTOMATION=true"
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform plan -input=false -destroy -out terraform.tfplan
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  dir: terraform/single/
  env:
  - "TF_IN_AUTOMATION=true"
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform apply -input=false terraform.tfplan